# Workflow name
name: "Chromatic Deployment"

# Event for the workflow
on: push

# List of jobs
jobs:
  yarn_cache_dir:
    runs-on: ubuntu-latest
    outputs:
      yarn_cache_dir: ${{ steps.yarn-cache-dir-path.outputs.dir }}
    steps:
      - id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
  cache-deps:
    needs: yarn_cache_dir
    runs-on: ubuntu-latest
    outputs:
      yarn_cache_dir: ${{ needs.yarn_cache_dir.outputs.yarn_cache_dir }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache deps
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ needs.yarn_cache_dir.outputs.yarn_cache_dir }}
            ~/.cache/Cypress
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-v1-
      - run: yarn --frozen-lockfile

  interaction-and-accessibility:
    needs: cache-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Cache deps
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ needs.cache-deps.outputs.yarn_cache_dir }}
            ~/.cache/Cypress
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-v1-
      - run: yarn --frozen-lockfile
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: yarn build-storybook --quiet
      - name: Serve Storybook and run tests
        run: npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "npx http-server storybook-static --port 6006 --silent"
          "npx wait-on tcp:6006 && yarn test-storybook"
  visual:
    needs: cache-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache deps
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ needs.cache-deps.outputs.yarn_cache_dir }}
            ~/.cache/Cypress
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-v1-
      - run: yarn --frozen-lockfile
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
  e2e:
    needs: cache-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore deps
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ needs.cache-deps.outputs.yarn_cache_dir }}
            ~/.cache/Cypress
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-v1-
      - run: yarn --frozen-lockfile
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: yarn dev
          install: false
